version: "2"
linters:
  enable:
    - bodyclose
    - contextcheck
    - errorlint
    - forcetypeassert
    - gocritic
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
  settings:
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - diagnostic
        - performance
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - noctx
    paths:
      - testdata
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
